language: python
python:
  - "3.6"
dist: xenial

services:
  - docker

before_install:
- docker-compose -f local.yml run app /bin/bash -c "./prepare_db"

script:
- docker-compose -f local.yml run --rm app ./manage.py test --settings=config.settings.test "$@"

after_script:
  - pip install pycodestyle pyflakes
  - pyflakes . | tee >(wc -l)           # static analysis
  - pycodestyle --max-line-length=120 --statistics --count .  # static analysis